### ISSUE TITLE
Question: How to disable correction when I typed the executable name incorrectly?

### ISSUE THREAD

**Issue by HubKing** [wszqkzqk/easy-zsh-config#3]
I want to disable this correction question when I typed the executable name incorrectly. 
![image](https://github.com/wszqkzqk/easy-zsh-config/assets/10900489/8ee6b549-8e72-48e2-9035-cb597e72c641)

A.I. told me to add this to .zshrc, but this did not work.

    setopt nocorrectall

**Comment by wszqkzqk** [comment]
Please add `unsetopt correct` to your `.zshrc`.

**Comment by HubKing** [comment]
Thanks. That worked. Stupid A.I. gave wrong answer.
